"""Shared types, enums and constant tables for the Saju v2 engine."""

from __future__ import annotations

from .analysis import (
    FiveElementAnalysis,
    ForceAnalysis,
    RootingAnalysis,
    StrengthResult,
    TenGodAnalysis,
)
from .birth_input import BirthInput, TimeCalculationOptions
from .calibration import (
    CalibrationQuestion,
    CalibrationQuestionSet,
    CalibrationResult,
    FeedbackAnswer,
)
from .enums import (
    Branch,
    CalendarType,
    Element,
    HiddenStemType,
    Palace,
    PillarPosition,
    Stem,
    StrengthBand,
    TenGod,
    YinYang,
)
from .luck import DaewoonItem, LuckCycles, LuckPillar
from .manse_result import EngineMetadata, ManseV2Result
from .pillars import FourPillarsResult, HiddenStem, Pillar
from .region_element import (
    DominanceType,
    ElementVector,
    IntentMode,
    LayerType,
    RegionAdminSnapshot,
    RegionAdminUnit,
    RegionElementEvidence,
    RegionElementProfile,
    RegionFitItem,
    RegionGeoFeature,
    RegionLevel,
    RegionProfilesMeta,
    RegionProfilesSnapshot,
    RegionRecommendationQuery,
    RegionRecommendationResult,
    RegionResolution,
    RegionUnitInput,
    TargetElements,
)
from .sinsal import SinsalAnalysis, SinsalItem, TraditionalExtras
from .structure import (
    GeokgukResult,
    GongmangAnalysis,
    StabilityScores,
    StructuralInteraction,
    StructureAnalysis,
    TransformationCheck,
)
from .time_correction import SolarTermBasis, TimeCorrectionResult
from .yongsin import (
    AggregatedYongsinResult,
    ElementCandidate,
    SpecialCaseCheck,
    YongsinCandidateModel,
)

__all__ = [
    "BirthInput",
    "TimeCalculationOptions",
    "Branch",
    "CalendarType",
    "Element",
    "HiddenStemType",
    "Palace",
    "PillarPosition",
    "Stem",
    "StrengthBand",
    "TenGod",
    "YinYang",
    "EngineMetadata",
    "ManseV2Result",
    "FiveElementAnalysis",
    "ForceAnalysis",
    "RootingAnalysis",
    "StrengthResult",
    "TenGodAnalysis",
    "FourPillarsResult",
    "HiddenStem",
    "Pillar",
    "SolarTermBasis",
    "TimeCorrectionResult",
    "GeokgukResult",
    "GongmangAnalysis",
    "StabilityScores",
    "StructuralInteraction",
    "StructureAnalysis",
    "TransformationCheck",
    "AggregatedYongsinResult",
    "ElementCandidate",
    "SpecialCaseCheck",
    "YongsinCandidateModel",
    "DaewoonItem",
    "LuckCycles",
    "LuckPillar",
    "CalibrationQuestion",
    "CalibrationQuestionSet",
    "CalibrationResult",
    "FeedbackAnswer",
    "SinsalAnalysis",
    "SinsalItem",
    "TraditionalExtras",
    "RegionResolution",
    "RegionLevel",
    "LayerType",
    "DominanceType",
    "IntentMode",
    "ElementVector",
    "RegionElementEvidence",
    "RegionGeoFeature",
    "RegionAdminUnit",
    "RegionAdminSnapshot",
    "RegionUnitInput",
    "RegionElementProfile",
    "TargetElements",
    "RegionRecommendationQuery",
    "RegionFitItem",
    "RegionRecommendationResult",
    "RegionProfilesMeta",
    "RegionProfilesSnapshot",
]
